# Generated by Django 2.1.7 on 2019-08-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_handle', '0002_filemanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file_uploader',
            field=models.ForeignKey(limit_choices_to={'user_type': 'UPLOADER'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='file_handle.CustomUser'),
        ),
    ]
