# Generated by Django 2.1.7 on 2019-08-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_handle', '0003_auto_20190811_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='file_recepient',
            field=models.ForeignKey(limit_choices_to={'user_type': 'RECEPIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='recepient', to='file_handle.CustomUser'),
        ),
    ]
